In [1]:
import os
import numpy as np
import sklearn
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, make_scorer
from sklearn import svm
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold, cross_validate, KFold
from sklearn.preprocessing import RobustScaler

In [2]:
def specificity(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true,y_pred).ravel()
    return tn/(tn+fp)

In [3]:
# Read data
int_ict_data = np.load('/kaggle/input/intict-wavelets/intict_wave_feats.npy')
int_ict_labels = np.load('/kaggle/input/intict-wavelets/intict_wave_labels.npy')


# Scales 2-5  Wavelet Features

In [96]:
vc_s25 = int_ict_data[:,:4]
FI_s25 = int_ict_data[:,5:9]

int_ict_data_s25 = np.hstack((vc_s25, FI_s25))
print(int_ict_data_s25.shape)

(800, 8)


In [97]:
C =100
gamma=0.003

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s25, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 100 and gamma = 0.003
accuracy = 0.9875


confusion matrix:
 [[78  2]
 [ 0 80]]

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        80
           1       0.98      1.00      0.99        80

    accuracy                           0.99       160
   macro avg       0.99      0.99      0.99       160
weighted avg       0.99      0.99      0.99       160

cross validation fold sensitivities:  [0.9625 0.9875 0.975  0.975 ]
cross validation fold specificities:  [0.9875 0.9625 0.975  1.    ]
average sensitivity:  0.9750000000000001
average specificity:  0.9812500000000001


# Scale 1 Wavelet Features

In [105]:
vc_s1 = int_ict_data[:,4].reshape(-1,1)
FI_s1 = int_ict_data[:,9].reshape(-1,1)

int_ict_data_s1 = np.hstack((vc_s1, FI_s1))
print(int_ict_data_s1.shape)

(800, 2)


In [113]:
C =100
gamma=0.03

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s1, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 100 and gamma = 0.03
accuracy = 1.0000


confusion matrix:
 [[80  0]
 [ 0 80]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        80
           1       1.00      1.00      1.00        80

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160

cross validation fold sensitivities:  [0.9125 0.95   0.975  0.9375]
cross validation fold specificities:  [0.95 0.95 0.95 0.95]
average sensitivity:  0.94375
average specificity:  0.95


# Scale 2 Wavelet Features

In [114]:
vc_s2 = int_ict_data[:,3].reshape(-1,1)
FI_s2 = int_ict_data[:,8].reshape(-1,1)

int_ict_data_s2 = np.hstack((vc_s2, FI_s2))
print(int_ict_data_s2.shape)

(800, 2)


In [137]:
C =40
gamma=0.018

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s2, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 40 and gamma = 0.018
accuracy = 0.9812


confusion matrix:
 [[78  2]
 [ 1 79]]

              precision    recall  f1-score   support

           0       0.99      0.97      0.98        80
           1       0.98      0.99      0.98        80

    accuracy                           0.98       160
   macro avg       0.98      0.98      0.98       160
weighted avg       0.98      0.98      0.98       160

cross validation fold sensitivities:  [0.9625 0.975  0.9875 0.975 ]
cross validation fold specificities:  [0.95  0.95  0.975 0.975]
average sensitivity:  0.975
average specificity:  0.9625


# Scale 3 Wavelet Features

In [138]:
vc_s3 = int_ict_data[:,2].reshape(-1,1)
FI_s3 = int_ict_data[:,7].reshape(-1,1)

int_ict_data_s3 = np.hstack((vc_s3, FI_s3))
print(int_ict_data_s3.shape)

(800, 2)


In [142]:
C =125
gamma=0.046

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s3, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 125 and gamma = 0.046
accuracy = 0.9563


confusion matrix:
 [[76  4]
 [ 3 77]]

              precision    recall  f1-score   support

           0       0.96      0.95      0.96        80
           1       0.95      0.96      0.96        80

    accuracy                           0.96       160
   macro avg       0.96      0.96      0.96       160
weighted avg       0.96      0.96      0.96       160

cross validation fold sensitivities:  [0.9875 1.     0.975  0.975 ]
cross validation fold specificities:  [0.9875 0.9625 1.     1.    ]
average sensitivity:  0.984375
average specificity:  0.9875


# Scale 4 Wavelet Features

In [4]:
vc_s4 = int_ict_data[:,1].reshape(-1,1)
FI_s4 = int_ict_data[:,6].reshape(-1,1)

int_ict_data_s4 = np.hstack((vc_s4, FI_s4))
print(int_ict_data_s4.shape)

(800, 2)


In [21]:
C =60
gamma=0.024

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s4, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 60 and gamma = 0.024
accuracy = 0.9375


confusion matrix:
 [[77  3]
 [ 7 73]]

              precision    recall  f1-score   support

           0       0.92      0.96      0.94        80
           1       0.96      0.91      0.94        80

    accuracy                           0.94       160
   macro avg       0.94      0.94      0.94       160
weighted avg       0.94      0.94      0.94       160

cross validation fold sensitivities:  [0.8875 0.975  0.9125 0.9125]
cross validation fold specificities:  [0.9625 0.95   1.     0.9875]
average sensitivity:  0.921875
average specificity:  0.9750000000000001


# Scale 5 Wavelet Features

In [5]:
vc_s5 = int_ict_data[:,0].reshape(-1,1)
FI_s5 = int_ict_data[:,5].reshape(-1,1)

int_ict_data_s5 = np.hstack((vc_s5, FI_s5))
print(int_ict_data_s5.shape)

(800, 2)


In [31]:
C =100
gamma=0.085

intict_train_data, intict_test_data, intict_train_labels, intict_test_labels = train_test_split(int_ict_data_s5, int_ict_labels, test_size = 0.2, random_state=42)

classifier = svm.SVC(C=C, kernel='rbf', gamma=gamma)
classifier.fit(intict_train_data, np.ravel(intict_train_labels))

intict_test_preds = classifier.predict(intict_test_data)
accuracy = accuracy_score(intict_test_labels, intict_test_preds)

print(f'C = {C} and gamma = {gamma}')
print(f'accuracy = {accuracy:.4f}\n')

confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)
print(f'\nconfusion matrix:\n {confusion_mat}\n')

print(classification_report(intict_test_labels, intict_test_preds))




from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


sensitivity_scorer = make_scorer(recall_score, pos_label=1)
specificity_scorer = make_scorer(specificity)

scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)


print('cross validation fold sensitivities: ',cv_results['test_sensitivity'])
print('cross validation fold specificities: ',cv_results['test_specificity'])

print('average sensitivity: ',np.mean(cv_results['test_sensitivity']))
print('average specificity: ',np.mean(cv_results['test_specificity']))


C = 100 and gamma = 0.085
accuracy = 0.8875


confusion matrix:
 [[70 10]
 [ 8 72]]

              precision    recall  f1-score   support

           0       0.90      0.88      0.89        80
           1       0.88      0.90      0.89        80

    accuracy                           0.89       160
   macro avg       0.89      0.89      0.89       160
weighted avg       0.89      0.89      0.89       160

cross validation fold sensitivities:  [0.8875 0.9625 0.9    0.95  ]
cross validation fold specificities:  [0.925  0.9125 0.9625 0.9375]
average sensitivity:  0.925
average specificity:  0.934375


In [32]:
# gamma_array = np.arange(0.001,0.5,0.001)
# c_array = np.arange(30,100,10)

# for i in gamma_array:
#     for j in c_array:
#         classifier = svm.SVC(C=j, kernel='rbf', gamma=i)
#         classifier.fit(intict_train_data, np.ravel(intict_train_labels))

#         intict_test_preds = classifier.predict(intict_test_data)
#         accuracy = accuracy_score(intict_test_labels, intict_test_preds)

#         confusion_mat = confusion_matrix(intict_test_labels, intict_test_preds)

#         from sklearn.preprocessing import RobustScaler
#         scaler = RobustScaler()
#         intict_train_feats_scaled = scaler.fit_transform(intict_train_data)


#         sensitivity_scorer = make_scorer(recall_score, pos_label=1)
#         specificity_scorer = make_scorer(specificity)

#         scoring = {'sensitivity': sensitivity_scorer, 'specificity':specificity_scorer}

#         cv_results = cross_validate(classifier, intict_train_feats_scaled, np.ravel(intict_train_labels), cv=StratifiedKFold(4), scoring=scoring)

        
#         avg_sen = np.mean(cv_results['test_sensitivity'])
#         avg_spec = np.mean(cv_results['test_specificity'])
        
#         if avg_sen>=0.92 and avg_spec>=0.92:
#             print(f'gamma = {i:.4f} and c = {j:.3f}')
#             print(f'\tsens = {avg_sen:.4f} \t\t spec = {avg_spec:4f} \t\t acc = {accuracy:.4f}')